None option for modal
Headstorm/foundry-ui pull request #252
Opened 2021-07-22 19:29 UTC by j-storey5

Sorry for all the clutter, changes got made when running yarn test and then github wanted to update every file to match the latest test date. All feature changes are in /src/components/Modal/Modal.tsx and .../Modal/Modal.stories.tsx

2021-07-27 16:19 UTC, aVileBroker requested changes

2021-07-27 16:19 UTC, aVileBroker commented on src/components/Modal/Modal.tsx
> +    let display_type = 'flex'; //what is the desired default for the close button's display-type??
default distance and position to something here
update display_type to `inline-flex`

change `display_type` to `display`

2021-07-27 16:56 UTC, aVileBroker commented on src/components/Modal/Modal.tsx
> +    let display = 'in-line flex'; //default display type
This should be `inline-flex`, which is a display attribute
https://developer.mozilla.org/en-US/docs/Web/CSS/display
```suggestion
    let display = 'inline-flex'; //default display type
```

2021-07-27 17:03 UTC, aVileBroker approved these changes

2021-07-27 17:04 UTC, aVileBroker requested changes
accidental approval - still needs inline-flex change

2021-07-27 19:13 UTC, aVileBroker approved these changes

2021-07-27 19:41 UTC, merged

2021-07-27 19:41 UTC, j-storey5 commented
Merge Success!

2021-07-29 22:43 UTC, HeadstormOps commented
:tada: This PR is included in version 1.2.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@headstorm/foundry-react-ui/v/1.2.1)
- [GitHub release](https://github.com/Headstorm/foundry-ui/releases/tag/v1.2.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: