Table sort improvements
Headstorm/foundry-ui pull request #439
Opened 2023-06-22 19:16 UTC by xavierdonnellon

This PR fixes #438 and accomplishes the following:
* Adds a third sort state – allows for toggling of the sort through ascending, descending, and the new unsorted state. This lets users disable a sort after they enable it if they want.
* Adds the `SortDirection` and `SortState` data types which clean up the code. 
* Passes the `isSorted` prop to `HeaderCell` and `ResponsiveHeaderCell` to allow for custom styling on the header when the column is being sorted by

2023-06-22 23:53 UTC, aVileBroker requested changes

2023-06-22 23:53 UTC, aVileBroker commented on src/components/Table/Table.tsx
> +        'From FoundryUI Table: Passing `direction` prop to `SortIcon` as a boolean is deprecated. Please pass in an argument of type `SortDirection` instead.',
```suggestion
        'From FoundryUI Table: Passing a boolean to the `direction` prop on `SortIcon` is deprecated. Use the `Table.SortDirection` enum instead.',
```

2023-06-22 23:53 UTC, aVileBroker commented on src/components/Table/Table.tsx
> +  // Convert deprecated defaultSort argument if provided as [key, bool]
```suggestion
  // Convert defaultSort argument if provided in the deprecated form [key, bool]
```

2023-06-22 23:53 UTC, aVileBroker commented on src/components/Table/Table.tsx
> +      'From FoundryUI Table: Passing `defaultSort` prop as type [string, boolean] is deprecated. Instead, pass an argument of type `SortState`.',
```suggestion
      'From FoundryUI Table: Passing `defaultSort` prop as type [string, boolean] is deprecated. Instead, pass an argument of type `Table.SortState`.',
```

2023-06-22 23:53 UTC, aVileBroker commented on src/components/Table/Table.tsx
>     */
this comment needs to be updated

2023-06-22 23:53 UTC, aVileBroker commented on src/components/Table/Table.tsx
> +      sortState.sortedColumn === key ? (sortState.direction + 1) % 3 : SortDirection.ascending,
lol

2023-06-22 23:53 UTC, aVileBroker commented on src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
> +            direction="1"
the browser will complain that `direction` isn't a valid attribute of `svg`, I think there's a way to add `data-` prefix or something similar to make it happy. This needs to be done in other components but might as well test it here

2023-06-22 23:53 UTC, aVileBroker commented on src/components/Table/types.ts
> +  sortedColumn?: string;
if it's not too late, we could change this to `sortedColumnKey` and get rid of the comment

2023-06-22 23:53 UTC, aVileBroker commented on src/components/Table/types.ts
> +}
I believe enums do this automatically
```suggestion
export enum SortDirection {
  noSort,
  ascending,
  descending,
}
```

2023-06-22 23:53 UTC, aVileBroker commented on src/components/Table/types.ts
> +   * The `[string, boolean]` type for this prop is deprecated. Instead, use `SortState`.
```suggestion
   * The `[string, boolean]` type for this prop is deprecated. Instead, use `Table.SortState`.
```

2023-06-23 17:07 UTC, xavierdonnellon commented on src/components/Table/Table.tsx
> +      sortState.sortedColumn === key ? (sortState.direction + 1) % 3 : SortDirection.ascending,
LOL indeed. Too cracked to remove

2023-06-26 15:51 UTC, aVileBroker approved these changes

2023-06-26 15:59 UTC, merged

2023-06-26 16:04 UTC, HeadstormOps commented
:tada: This PR is included in version 1.21.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@headstorm/foundry-react-ui/v/1.21.0)
- [GitHub release](https://github.com/Headstorm/foundry-ui/releases/tag/v1.21.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: